### PR TITLE
Fix failure to build with libxml2 version 2.12

### PR DESCRIPTION
**Pull request by nphilipp**
This made one argument of xmlStructuredErrorFunc() const, which wasn’t previously so.

### CODE REVIEW

**Comment by x42** [comment]
Perhaps a follow up issue to  https://gitlab.gnome.org/GNOME/libxml2/-/issues/526 - though this breaks the API.
It would be unfortunate if we'd need to #ifdef this code depending on libXML version.

**Comment by x42** [comment]
Note that debug versions of Ardour also need further changes. e.g.  libs/pbd/xml++.cc has `xmlErrorPtr xerr = xmlGetLastError (); ` inside a NDEBUG section

**Comment by nphilipp** [comment]
> ```
> ../gtk2_ardour/ardour_ui.cc:406:35: error: invalid conversion from … {aka ‘void (*)(void*, const _xmlError*)’} to … {aka ‘void (*)(void*, _xmlError*)’} [-fpermissive]
> ```

I wonder why it failed to build without the patch then. Maybe I should revert adding the `const` and the call should just cast the function to `xmlStructuredErrorFunc` instead?

> Note that debug versions of Ardour also need further changes. e.g. libs/pbd/xml++.cc has `xmlErrorPtr xerr = xmlGetLastError (); ` inside a NDEBUG section

Mhm, missed that. I guess that here, making it `const xmlError *` should work, shouldn’t it? — I’ll find out, I’m just installing a Debian 11 VM to verify with libxml2 2.9.x 😉 (the Fedora builds cover 2.10 and 2.12).

**Comment by x42** [comment]
Ardour can't be the only project affected by this. Perhaps we should ask libxml devs to provide backwards compatibility?

**Comment by nphilipp** [comment]
> Ardour can't be the only project affected by this. Perhaps we should ask libxml devs to provide backwards compatibility?

They’re kind of in a bind here, declaring that pointer `const` is arguably the right thing – the callback shouldn’t modify what’s passed in – the assumption was probably always there, but not made explicit. Then, libxml2 is a C library and there the difference in constness between the callback and the function signature only yields you a warning, it’s C++ which makes it an error.

I've updated my patch to make that other `xmlError` pointer const (neither gcc nor g++ seem to have a problem with that, regardless of libxml2 version) and make the cast I described above which makes the file compile without warning (on Debian 11 and Fedora 39).

**Comment by x42** [comment]
> They’re kind of in a bind here, declaring that pointer const is arguably the right thing

Yep, the established way for this is to introduce a new function and deprecated the old.

**Comment by nphilipp** [comment]
> > They’re kind of in a bind here, declaring that pointer const is arguably the right thing
> 
> Yep, the established way for this is to introduce a new function and deprecated the old.

I'll leave the can of worms which is that discussion firmly closed. 😅
